repos:
  - repo: local
    hooks:
      - id: format
        name: format
        entry: make format
        language: system
        stages: [pre-commit]
      - id: lint
        name: lint
        entry: make precommit-lint
        language: system
        stages: [pre-commit, pre-push]
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.14
    hooks:
      - id: uv-lock # Update the uv lockfile
  - repo: https://github.com/crate-ci/typos
    rev: v1.32.0
    hooks:
      - id: typos
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
        args: [--assume-in-merge]
      - id: check-ast
      - id: check-case-conflict
      - id: detect-private-key
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: pretty-format-json
        args: [--autofix]
        exclude: |
          (?x)^(.vscode/settings.json)$
      - id: check-yaml
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
